getwd()
setwd('../data')
filename = './urml_mean_ellip_result.csv'
m2mm = 1000.0
g_const = 9.806
dat <- read.csv(filename)
dat$dis <- dat$dis*m2mm
dat$force <- dat$force/g_const
dat$tacc <- dat$tacc/g_const
plot(log(dat$dis),log(dat$tacc-dat$force))
plot(log(dat$dis),log(dat$tacc/dat$force))
plot(log(dat$tacc/dat$force))
y <- log(dat$tacc/dat$force)
summary(y)
plot(log(dat$dis),log(dat$tacc/dat$force))
plot(dat$dis,log(dat$tacc/dat$force))
plot(sqrt(dat$dis),log(dat$tacc/dat$force))
plot(dat$dis**2.0,log(dat$tacc/dat$force))
plot(dat$dis**0.1,log(dat$tacc/dat$force))
plot(log(dat$dis),log(dat$tacc/dat$force))
plot(log(dat$dis),log(dat$tacc-dat$force))
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force))
dev.new(); plot(log(dat$dis),log(1+dat$tacc/dat$force))
dev.new(); plot(log(dat$dis),log(dat$force/dat$tacc))
dev.new(); plot(log(dat$dis),log(log(dat$force/dat$tacc)))
dev.new(); plot(log(dat$dis),log(dat$force/dat$tacc)**0.5)
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force)**2.0)
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force)**0.1)
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
y <- dat$tacc/dat$force
y
summary(y)
dev.new(); plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
ndat <- data.frame(x=log(dat$dis),y=log(dat$tacc/dat$force)**0.5)
lin.dat <- lm(ndat)
mfrow=c(2,2)
plot(lin.dat)
par(mfrow=c(2,2))
plot(lin.dat)
require(segmented)
seg <- segmented(lin.dat, seg.Z=~x,psi=c(1.5,2.0))
seg <- segmented(lin.dat, seg.Z=~x,psi=c(1.5,2.0))
head(ndat)
lin.dat
seg <- segmented(lin.dat, seg.Z = ~x, psi=c(1.5,2.0))
lin.dat <- lm(y~x,ndat)
plot(lin.dat)
par(mfrow=c(2,2))
plot(lin.dat)
lin.dat
par(mfrow=c(2,2))
plot(lin.dat)
dev.new()
par(mfrow=c(2,2))
plot(lin.dat)
dev.new()
plot(y~x,ndat)
seg <- segmented(lin.dat, seg.Z = ~x, psi=c(1.5,2.0))
seg
points(ndat$x,seg$fitted,col='red')
points(ndat$x,broken.line(seg,link=FALSE)$fit,col=2,pch=20)
lin.dat
ndat
ndat <- ndat[complete.cases(ndat),]
lin.dat <- lm(y~x,ndat)
seg <- segmented(lin.dat, seg.Z = ~x, psi=c(1.5,2.0))
points(ndat$x,broken.line(seg,link=FALSE)$fit,col=2,pch=20)
data = list(x=c(50,60,70,80,90) , y= c(703.786,705.857,708.153,711.056,709.257))
plot(data, type='b')
dev
tf1 = dat$dis < dy
dev.new();plot(dat$dis[tf1],dat$tacc[tf1])
dev.new();plot(dat$dis[!tf1],dat$tacc[!tf1])
dev.new();plot(log(dat$dis[tf1]),log(dat$tacc[tf1]))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]/dat$force[!tf1]))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]-dat$force[!tf1]))
dev.new();plot(log(dat$dis[!tf1]),log(abs(dat$tacc[!tf1]-dat$force[!tf1])))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]/dat$force[!tf1]))
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force))
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
log(dy)
du <- 6.7065
log(du)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force))
dev.new();plot(log(dat$dis[tf1]),log(dat$tacc[tf1]-dat$force[tf1]))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]-dat$force[!tf1]))
dev.new();plot(log(dat$dis),log(dat$tacc-dat$force))
dev.new();plot(log(dat$dis[!tf1]),log(dat$tacc[!tf1]/dat$force[!tf1]))
dev.new();plot(log(dat$dis[tf1]),log(dat$tacc[tf1]/dat$force[tf1]))
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force))
ndat
lm.mod <- lm(y~x**2.0+x,ndat)
lm.mod
fit1 <- lm(ndat$y~ndat$x)
fit2 <- lm(ndat$y~ndat$x+I(ndat$x^2))

summary(fit2)
summary(fit3)
par(mfrow=c(2,2))
plot(fit2)
plot(fit3)
dev.new()
par(mfrow=c(2,2))
plot(fit3)
fit_exp <- lm(ndat$y~exp(ndat$x))
dev.new()
par(mfrow=c(2,2))
plot(fit_exp)
plot(fit3$fitted,col='red')
points(ndat$x,fit3$fitted,col='red')
dev.new()
plot(ndat$x,ndat$y)
head(dat)
ndat2 <- data.frame(x=log(dat$dis), y = log(dat$tacc/dat$force))
plot(y~x,ndat2)
fit_exp <- lm(y~exp(x), ndat2)
points(ndat2$x,fit_exp$fitted,col='red')
fit_exp <- lm(ndat2$y~I(exp(ndat$2x))

plot(log(ndat2$x),ndat2$y)
plot(ndat2$x,log(ndat2$y)
)
plot(y~x,ndat2,xlim=c(0,3))
dev.new()
plot(y~x,ndat2,xlim=c(0,3))
plot(y~x,ndat2,xlim=c(3,10))
plot(y~x,ndat2)
plot(ndat2$x,log(ndat2$y))
tf1
dat$force[tf1] > dat$tacc[tf1]
sum(dat$force[tf1] > dat$tacc[tf1])
sum(dat$force[tf1] < dat$tacc[tf1])
plot(dat$force[tf1]/ dat$tacc[tf1])
plot(log(dat$force[tf1]/ dat$tacc[tf1]))
log(1)
tf2 <- (dat$dis >= dy)&(dat$dis<du)
sum(tf2)
tf3 <- (dat$dis >= du)
sum(tf3)
sum(tf1)
nrow(dat)
188+298+33
plot(log(dat$force[tf2]/ dat$tacc[tf2]))
plot(dat$force[tf2]/ dat$tacc[tf2])
plot(dat$force[tf3]/ dat$tacc[tf3])
plot(dat$dis, dat$force[tf2]/ dat$tacc[tf2])
plot(dat$dis[tf2], dat$force[tf2]/ dat$tacc[tf2])
plot(dat$dis[tf2], dat$tacc[tf2]/ dat$force[tf2])
du
plot(dat$dis[tf2|tf1], dat$tacc[tf2|tf1]/ dat$force[tf2|tf1])
dev.new()
plot(dat$dis[tf3], dat$tacc[tf3]/ dat$force[tf3])
plot(dat$dis[tf3], log(dat$tacc[tf3]/ dat$force[tf3]))
dev.new()
plot(dat$dis[tf3], log(dat$tacc[tf3]/ dat$force[tf3]))
plot(log(dat$dis[tf3]), log(dat$tacc[tf3]/ dat$force[tf3]))
dev.new()
plot(log(dat$dis[tf3]), log(dat$tacc[tf3]/ dat$force[tf3]))
dev.new(); plot(dat$dis[tf3|tf2], log(dat$tacc[tf3|tf2]/ dat$force[tf3|tf2]))
dev.new(); plot(log(dat$dis[tf3|tf2]), log(dat$tacc[tf3|tf2]/ dat$force[tf3|tf2]))
ndat2 <- data.frame(x=log(dat$dis), y = log(dat$tacc/dat$force))
dev.new();plot(y~x,ndat2)
fit1 <- lm(ndat2$y ~ ndat2$x)
fit2 <- lm(ndat2$y ~ ndat2$x+I(ndat2$x^2))
fit3 <- lm(ndat2$y ~ ndat2$x+I(ndat2$x^2)+I(ndat2$x^3))
summary(fit2)
summary(fit3)
points(ndat2$x,fit2$fitted,col='red')
dev.new();plot(fit2$fitted,fit2$residu,col='red')
lin1 <- lm(y~x,ndat2)
dev.new()
par(mfrow=c(2,2))
plot(lin1)
seg1 <- segmented(lin1, seg.Z=~x, psi=None)
seg1 <- segmented(lin1, seg.Z=~x, psi=NA)
seg1 <- segmented(lin1, seg.Z=~x, psi=1.0, )
summary(seg1)
log(dy)
log(du)
seg1 <- segmented(lin1, seg.Z=~x, psi=c(2.0,3.0))
dev.new();plot(seg1$fitted,seg1$residu)
dev.new();plot(ndat2$x,seg1$residu)
points(ndat2$x, seg1$fitted,col='red')
dev.new();plot(y~x,ndat2)
points(ndat2$x, seg1$fitted,col='red')
?pmax
ndat3 <- data.frame(log(dat$dis), log(dat$tacc))
ndat3 <- data.frame(x=log(dat$dis), y=log(dat$tacc))
dev.new();plot(y~x,ndat3)
lin3 <- lm(y~x,ndat3)
dev.new();par(mfrow=c(2,2))
plot(lin3)
ls()
seg3 <- segmented(lin3, seg.Z=~x, c(log(du),4))
log(du)
points(ndat3$x, seg3$fitted,col='red')
points(ndat3$x, seg3$fitted,col='red')
dev.new()
dev.new();plot(y~x,ndat3)
points(ndat3$x, seg3$fitted,col='red')
dev.new();plot(seg3$fitted, seg3$residu)
ndat4 <- data.frame(log(dat$dis), log(dat$tacc-dat$force))
ndat4 <- ndat4[complete.cases(ndat4),]
ndat4 <- data.frame(x=log(dat$dis), y=log(dat$tacc-dat$force))
ndat4 <- ndat4[complete.cases(ndat4),]
dev.new();plot(y~x,ndat4)
lin4 <- lm(y~x,ndat4)
seg4 <- segmented(lin4, seg.Z=~x, psi=c(0.5,2))
points(ndat4$x, seg4$fitted,col='red')
dev.new();plot(seg4$fitted, seg4$residu)
dev.new();plot(ndat4$x, seg4$residu)
dev.new();plot(ndat3$x, seg3$residu)
dev.new();plot(seg3$fitted, seg3$residu)
dev.new();plot(seg4$fitted, seg4$residu)
dev.new();plot(seg2$fitted, seg2$residu)
ls()
dev.new();plot(seg1$fitted, seg1$residu)
dev.new();plot(seg$fitted, seg$residu)
dev.new();plot(seg2$fitted, seg2$residu)
dev.new();plot(seg1$fitted, seg1$residu)
summary(seg)
dev.new();plot(y~x,lin.dat)
dev.new();plot(y~x,ndat)
dev.new();plot(log(dat$dis)**2.0,log(dat$tacc/dat$force))
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**2.0)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force))
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.3)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.1)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.2)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.3)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)*0.3)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.3)
dev.new();plot(log(dat$dis),log(dat$tacc/dat$force)**0.5)
dev.new();plot(seg1$fitted, seg1$residu)
dev.new();plot(seg$fitted, seg$residu)

part_new <- data.frame(x=log(dat$dis[dat$dis<dy])
)
part_new
part_new$y <- predict(seg, part_new)
dev.new();plot(y~x,part_new)
dev.new();plot(part_new$x,exp(part_new$y**2)*part_new$x)
dev.new();plot(dat$dis, dat$tacc)
dev.new();plot(dat$dis, dat$tacc)
part_new = data.frame(x=log(dat$dis))
part_new$y <- predict(seg, part_new)
points(dat$dis, exp(part_new$y**2)*dat$force,col='red')

points(dat$dis, exp(part_new$y**2)*dat$force,col='red')
part_new$fitted <- exp(part_new$y**2)*dat$force
dev.new();plot(dat$dis, part_new$fitted-dat$tacc)
dev.new();plot(log(dat$dis), log(part_new$fitted))
points(log(dat$dis), log(dat$tacc),col='red')
getwd()
savehistory(file = "../code/Chapter3.Rhistory")
summary(seg)
AIC(seg)
AIC(seg1)
AIC(seg2)
AIC(seg3)
AIC(seg4)
AIC(seg)
summary(seg3)
summary(seg4)
savehistory(file = "../code/Chapter3.Rhistory")
